api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'rescatados', views.RescatadosListaJson)
router.register(r'socios', views.SociosListaJson)

urlpatterns = [
    path('', include(router.urls)),
]

misperris2020/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('socios.urls')),
    path('rescatados/', include('rescatados.urls')),
    path('api/', include('api.urls')),
    path('', include('pwa.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rescatados/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.rescatado_list, name='rescatado_list'),
    path('<int:pk>/', views.rescatado_detail, name='rescatado_detail'),
    path('add', views.rescatado_add, name='rescatado_add'),
    path('<int:pk>/edit/', views.rescatado_edit, name='rescatado_edit'),
    path('<int:pk>/delete/', views.rescatado_delete, name='rescatado_delete'),
]

socios/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.socios_form, name='socios_form'),
    path('socio/<int:pk>/', views.socios_respuesta, name='socios_res'),
]

api/models.py
from django.db import models

# Create your models here.

destacados/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Destacado(models.Model):
    imagen_destacada = models.ImageField(null=False,upload_to = 'img-destacados')
    titutlo_destacado = models.CharField(max_length=200)

    def __str__(self):
        return self.titutlo_destacado

galeria/models.py
from django.db import models

# Create your models here.
class Galeria(models.Model):
    
    imagen = models.ImageField(null=False,upload_to = 'img-gal/')
    nombre_mascota = models.CharField(max_length=200, null=False)
    comentario_breve = models.TextField(null=False)

    def __str__(self):
        return self.nombre_mascota

rescatados/models.py
from django.db import models
from django.utils import timezone

#Opciones selector estado rescatado
ESTADO_RESCATADO_CHOICES = (
    ('recatado','Rescatado'),
    ('disponible', 'Disponible'),
    ('adoptado','Adoptado'),
)

# Create your models here.
class Rescatado(models.Model):
    
    fotografia = models.ImageField(null=False,upload_to = 'rescatados/', default = 'rescatados/sin-imagen.jpg')
    nombre = models.CharField(max_length=200, null=False)
    raza_predominante = models.CharField(max_length=50, null=False)
    descripcion = models.TextField(null=False)
    estado = models.CharField(max_length=15, choices=ESTADO_RESCATADO_CHOICES, default='rescatado')

    def __str__(self):
        return self.nombre
    objects = models.Manager()

socios/models.py
from django.db import models
from django.utils import timezone

#Opciones selector Tipo de casa
TIPO_CASA_CHOICES = (
    ('casa-patio-l','Casa con patio grande'),
    ('casa-patio-s', 'Casa con patio pequeño'),
    ('casa','Casa sin patio'),
    ('depto','Departamento'),
)

# Create your models here.
class Socio(models.Model):
    email = models.EmailField(max_length=200)
    rut = models.CharField(max_length=10)
    nombre_completo = models.CharField(max_length=200, null=False)
    fecha_nacimiento = models.DateField(default='1980-12-05')
    telefono = models.CharField(max_length=15, default='+562454554226')
    ciudad = models.CharField(max_length=200)
    tipo_de_casa = models.CharField(max_length=25, choices=TIPO_CASA_CHOICES, default='casa-patio-l')

    def __str__(self):
        return self.nombre_completo

rescatados/forms.py
from django import forms
from .models import Rescatado

class RescatadoAdd(forms.ModelForm):

    class Meta:
        model = Rescatado
        fields = ('fotografia', 'nombre','raza_predominante', 'descripcion', 'estado')

socios/forms.py
from django import forms
from .models import Socio

class SocioForm(forms.ModelForm):

    class Meta:
        model = Socio
        fields = ('email', 'rut','nombre_completo', 'fecha_nacimiento', 'telefono', 'ciudad', 'tipo_de_casa')

api/views.py
from rest_framework import viewsets, permissions
from .serializers import RescatadosListaSerializer, SociosListaSerializer

#Modelos que necesito llamar
from rescatados.models import Rescatado
from socios.models import Socio

# Create your views here.

class RescatadosListaJson(viewsets.ModelViewSet):
    """
    API endpoint que lista los animales rescatados.
    """

    queryset = Rescatado.objects.all().order_by('nombre')
    serializer_class = RescatadosListaSerializer
    #permission_classes = [permissions.IsAuthenticated]

class SociosListaJson(viewsets.ModelViewSet):
    """
    API endpoint que lista los socios de la organización.
    """
    queryset = Socio.objects.all().order_by('email')
    serializer_class = SociosListaSerializer
    #permisson_classes = [permissions.IsAuthenticated]

destacados/views.py
from django.shortcuts import render

# Create your views here.

galeria/views.py
from django.shortcuts import render

# Create your views here.

rescatados/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import RescatadoAdd
from .models import Rescatado

# Create your views here.

def rescatado_add(request):
    if request.method == "POST":
        form = RescatadoAdd(request.POST, request.FILES)
        if form.is_valid():
            rescatado = form.save(commit=False)
            rescatado.save()
            return redirect('rescatado_detail', pk=rescatado.pk)
    else:
        form = RescatadoAdd()
    return render(request, 'rescatados/rescatado_add.html', {'form': form})

def rescatado_list(request):
    rescatados = Rescatado.objects.all()
    return render(request, 'rescatados/rescatado_list.html', {'rescatados': rescatados})

def rescatado_detail(request, pk):
    rescatado = get_object_or_404(Rescatado, pk=pk)
    return render(request, 'rescatados/rescatado_detail.html', {'rescatado': rescatado})

def rescatado_edit(request, pk):
    rescatado = get_object_or_404(Rescatado, pk=pk)
    if request.method == "POST":
        form = RescatadoAdd(request.POST, instance=rescatado)
        if form.is_valid():
            rescatado = form.save(commit=False)
            rescatado.save()
            return redirect('rescatado_list')
    else:
        form = RescatadoAdd(instance=rescatado)
    return render(request, 'rescatados/rescatado_edit.html', {'form': form})

def rescatado_delete(request, pk):  
    rescatado = Rescatado.objects.get(pk=pk)  
    rescatado.delete()  
    return redirect('rescatado_list')  

socios/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import SocioForm
from .models import Socio
from rescatados.models import Rescatado


# Create your views here.
def socios_form(request):
    if request.method == "POST":
        form = SocioForm(request.POST)
        if form.is_valid():
            socio = form.save(commit=False)
            socio.save()
            return redirect('socios_res', pk=socio.pk)
    else:
        form = SocioForm()
        rescatados = Rescatado.objects.all()
    return render(request, 'socios/socios_form.html', {'form': form, 'rescatados': rescatados})

def socios_respuesta(request, pk):
    socio = get_object_or_404(Socio, pk=pk)
    return render(request, 'socios/socios_respuesta.html', {'socio': socio})

rescatados/templates/rescatados/rescatado_add.html
{% load static %}
<!doctype html>
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Mis Perris</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!--Font Awesome-->
    <link rel="stylesheet" href="{% static 'librerias/fontawesome/all.min.css' %}">

    <!-- CSS propio -->
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
  </head>
  <body>

    <!-- Navegación -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <a class="navbar-brand" href="/">
          <img src="{% static 'imagenes/logo.png' %}" alt="Logo Mis perris" loading="lazy">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
              <a class="nav-link" href="/">Formulario</a>
              <a class="nav-link active" href="{% url 'rescatado_list' %}">Administración</a>
              <a class="nav-link" href="/admin">Django Admin</a>
          </div>
      </div>
  </nav>

    <!-- Administración -->
    <div class="admin galeria">
        <h2>Nuevo Rescatado</h2>
        <form method="POST" enctype="multipart/form-data" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <a class="btn btn-info" href="{% url 'rescatado_list' %}"><i class="fas fa-th-list"></i> Listar</a>
            <button type="submit" class="btn btn-success"><i class="fas fa-plus-circle"></i> Agregar Rescatado</button>
        </form>
    </div>

    <!--Footer-->
    <nav class="nav bg-secondary text-white footer">
        Desarrollo web y mobile - Duoc UC - al.aravena 2020
    </nav>
    
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
      </body>
    </html>

rescatados/templates/rescatados/rescatado_detail.html
{% load static %}
<!doctype html>
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Mis Perris</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!--Font Awesome-->
    <link rel="stylesheet" href="{% static 'librerias/fontawesome/all.min.css' %}">

    <!-- CSS propio -->
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
  </head>
  <body>

    <!-- Navegación -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <a class="navbar-brand" href="/">
          <img src="{% static 'imagenes/logo.png' %}" alt="Logo Mis perris" loading="lazy">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
              <a class="nav-link" href="/">Formulario</a>
              <a class="nav-link active" href="{% url 'rescatado_list' %}">Administración</a>
              <a class="nav-link" href="/admin">Django Admin</a>
          </div>
      </div>
  </nav>

<!-- Detalle -->
<div class="admin galeria">  
    <h3 class="card-title">{{ rescatado.nombre }}</h3>
    <p><b>Imagen:</b> <img src="{{ rescatado.fotografia.url }}" class="img-fluid col-md-2" alt="{{ rescatado.nombre }}"></p>
    <p><b>Raza Predominante:</b> {{ rescatado.raza_predominante }}</p>
    <p><b>Estado:</b> {{ rescatado.estado }}</p>
    <p><b>Descripcion:</b> {{ rescatado.descripcion }}</p>

    <p>
      <a class="btn btn-info" href="{% url 'rescatado_list' %}"><i class="fas fa-th-list"></i> Listar</a>
      <a class="btn btn-warning" href="{% url 'rescatado_edit' pk=rescatado.pk %}"><i class="fas fa-edit"></i> Editar</a>
      <a class="btn btn-danger" href="{% url 'rescatado_delete' pk=rescatado.pk %}"><i class="fas fa-trash-alt"></i> Eliminar</a>
    </p>

</div>

    <!--Footer-->
    <nav class="nav bg-secondary text-white footer">
        Desarrollo web y mobile - Duoc UC - al.aravena 2020
    </nav>
    
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
      </body>
    </html>

rescatados/templates/rescatados/rescatado_edit.html
{% load static %}
<!doctype html>
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Mis Perris</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!--Font Awesome-->
    <link rel="stylesheet" href="{% static 'librerias/fontawesome/all.min.css' %}">

    <!-- CSS propio -->
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
  </head>
  <body>

    <!-- Navegación -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <a class="navbar-brand" href="/">
            <img src="{% static 'imagenes/logo.png' %}" alt="Logo Mis perris" loading="lazy">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link" href="/">Formulario</a>
                <a class="nav-link active" href="{% url 'rescatado_list' %}">Administración</a>
                <a class="nav-link" href="/admin">Django Admin</a>
            </div>
        </div>
    </nav>

<!-- Editar -->
<div class="admin galeria">
    <h2>Editar Rescatado</h2>
    <form method="POST" enctype="multipart/form-data" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <a class="btn btn-info" href="{% url 'rescatado_list' %}"><i class="fas fa-th-list"></i> Listar</a>
        <button type="submit" class="btn btn-primary btn btn-warning"><i class="fas fa-edit"></i> Editar Rescatado</button>
    </form>
</div>

    <!--Footer-->
    <nav class="nav bg-secondary text-white footer">
        Desarrollo web y mobile - Duoc UC - al.aravena 2020
    </nav>
    
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
      </body>
    </html>

socios/templates/socios/socios_form.html
{% load static %}
<!doctype html>
<html lang="es">
  {% load pwa %}
  <head>
    {% progressive_web_app_meta %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Mis Perris</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!--Font Awesome-->
    <link rel="stylesheet" href="{% static 'librerias/fontawesome/all.min.css' %}">

    <!-- CSS propio -->
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <link rel="stylesheet" href="{% static 'css/btnpwa.css' %}">
  </head>
  <body>

    <!-- Navegación -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <a class="navbar-brand" href="/">
            <img src="{% static 'imagenes/logo.png' %}" alt="Logo Mis perris" loading="lazy">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" href="/">Formulario</a>
                <a class="nav-link" href="rescatados">Administración</a>
                <a class="nav-link" href="admin">Django Admin</a>
            </div>
        </div>
    </nav>

<!-- Listado -->
<div class="admin galeria"> 
  <h3>Rescatados</h3>  
  <div class="card-columns">  
      {% for rescatado in rescatados %}
      <div class="card text-white w-300 border-0">
          <img src="{{ rescatado.fotografia.url }}" class="card-img opaco" alt="{{ rescatado.nombre }}">
          <div class="card-img-overlay">
            <h5 class="card-title">{{ rescatado.nombre }}</h5>
            <p class="card-text">{{ rescatado.estado }}</p>
          </div>
        </div>
      {% endfor %}
  </div>
</div>

<!-- Contacto -->
<div class="contacto col-12">
  <h3>Únetenos</h3>
  <p class="small">Rellena los campos para ingresarte como voluntario de nuestra labor</p>
  <form method="POST" class="post-form">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="id_email">Correo electrónico</label>
        <input type="email" class="form-control" id="id_email" name="email">
      </div>
      <div class="form-group col-md-6">
        <label for="id_rut">Rut</label>
        <input type="text" class="form-control" id="id_rut" name="rut">
      </div>
      <div class="form-group col-md-12">
        <label for="id_nombre_completo">Nombre Completo</label>
        <input type="text" class="form-control" id="id_nombre_completo" name="nombre_completo">
      </div>
      <div class="form-group col-md-6">
        <label for="if_fecha_nacimiento">Fecha de Nacimiento</label>
        <input type="date" class="form-control" id="id_fecha_nacimiento" name="fecha_nacimiento">
      </div>
      <div class="form-group col-md-6">
        <label for="id_telefono">Teléfono</label>
        <input type="number" class="form-control" id="id_telefono" name="telefono">
      </div>
      <div class="form-group col-md-6">
        <label for="id_ciudad">Ciudad</label>
        <input type="text" class="form-control" id="id_ciudad" name="ciudad">
      </div>
      <div class="form-group col-md-6">
        <label for="id_tipo_de_casa">Tipo de vivienda</label>
        <select class="form-control" id="id_tipo_de_casa" name="tipo_de_casa">
          <option value="casa-patio-l">Casa con patio grande</option>
          <option value="casa-patio-s">Casa con patio pequeño</option>
          <option value="casa">Casa sin patio</option>
          <option value="depto">Departamento</option>
        </select>
      </div>
      <button type="submit" class="btn btn-primary btn btn-success">Enviar tus datos</button>
    </div>
  </form>
</div>


      <!--Footer-->
    <nav class="nav bg-secondary text-white footer">
        Desarrollo web y mobile - Duoc UC - al.aravena 2020
    </nav>

     <!--Boton para PWA-->
    <div id="prompt" class="prompt hide bg-light border-top">
      <div class="font-weight-bold">Agregar Aplicación</div>
      <small>Esta aplicación web puede ser instalada</small>
      <div class="text-right">
        <button id="buttonCancel" type="button" class="font-weight-bold text-muted btn-sm btn btn-link">CANCELAR</button>
        <button id="buttonAdd" type="button" class="font-weight-bold text-primary btn-sm btn btn-link">ACEPTAR</button>
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <script src="{% static 'js/btnpwa.js' %}" ></script>

  </body>
</html>

socios/templates/socios/socios_respuesta.html
{% load static %}
<!doctype html>
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Mis Perris</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!--Font Awesome-->
    <link rel="stylesheet" href="{% static 'librerias/fontawesome/all.min.css' %}">

    <!-- CSS propio -->
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
  </head>
  <body>

    <!-- Navegación -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <a class="navbar-brand" href="/">
          <img src="{% static 'imagenes/logo.png' %}" alt="Logo Mis perris" loading="lazy">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
              <a class="nav-link active" href="/">Formulario</a>
              <a class="nav-link" href="rescatados">Administración</a>
              <a class="nav-link" href="admin">Django Admin</a>
          </div>
      </div>
  </nav>


<!-- Contacto -->
<div class="contacto col-12">
  <h2>{{ socio.nombre_completo }}</h2>
  <p>Gracias por unírtenos</p>
</div>


      <!--Footer-->
    <nav class="nav bg-secondary text-white footer">
        Desarrollo web y mobile - Duoc UC - al.aravena 2020
    </nav>




    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

  </body>
</html>